import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute:"about title metadata",
  },
  description: "Generated by about title metadata",
};

const About = () => {
  return (
    <div>About</div>
  )
}

export default About