import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{backgroundColor:'#D2B4DE'}}>
          <h1>header</h1>
        </header>
        {children}
        <footer style={{background:'#ABEBC6'}}>
          <h1>footer</h1>
        </footer>
        </body>
    </html>
  );
}
